### ISSUE TITLE
Version regressed to 1.76.0

### ISSUE THREAD

**Issue by pixelmatrix** [getsentry/homebrew-tools#7]
I noticed some build failures this evening in our CLI, and it looks like it's because this formulae is suddenly installing an old version. Is this a mistake?

**Comment by joycastle-gaoyang** [comment]
I had the same problem, temporarily you can fix it like this

`cd /usr/local/Homebrew/Library/Taps/getsentry/homebrew-tools`
`git checkout 92406ccee0fe0ed00e830ac40f2846636665c1b2`
`brew reinstall sentry-cli`

finally you can check your sentry-cli version

`sentry-cli --version`

**Comment by armcknight** [comment]
Sorry for the lack of replies here. I think this was resolved in https://github.com/getsentry/sentry-cli/issues/1803.
